### ISSUE TITLE
Any plans for Symphony 2.3 ?? - Frontend Localisation

### ISSUE THREAD

**Issue by nitriques** [klaftertief-symphony/language_redirect#15]
Do you plan to rewrite this extension for Symphony 2.3 ?

There has been a lot of work done for multilingual sites for 2.3.

So if you do not want to do it, I think I will rewrite a new one.

Thanks.

**Comment by klaftertief** [comment]
Haven't decided yet how to proceed with this extension. It's not needed anymore to build multilingual sites. I need to have a proper look at the new multilingual extensions to make a proper decision. So I'm open for suggestions. Both in concept and code.

**Comment by nitriques** [comment]
Thanks for the quick reply.

I looked at the Frontend Localisation extension, which is used by all other Multilingual extension now. 
https://github.com/vlad-ghita/frontend_localisation/ @vlad-ghita did a really nice job.

I think the only thing that is missing is the _actual_ redirection event.
I am not sure where it belongs... In a separate extension? Or should we pull the event into vlad's extension ?

I really need those features (redirection and seperate URLs for each language) quick for a project. So I might move quickly. I go ask @vlad-ghita right away for this...

Thanks again.

**Comment by klaftertief** [comment]
Yep. It's only the redirect. So the extension will just do what it sais :-) I think it's ok to have a separate extension for that. You can get the separate URLs with the https://github.com/vlad-ghita/flang_detection_gtlds extension.

**Comment by nitriques** [comment]
Great... 

This would then lead to a complete rewrite... And even a rename? Frontend_localisation_redirect ?

I might to this as soon as tomorow (I am gmt-5)

Nicolas Brassard

**Comment by vlad-ghita** [comment]
@nitriques

I'm integrating the discussion from [FLang detection : gTLDs](https://github.com/vlad-ghita/flang_detection_gtlds/issues/3)  here because it's on the same topic.

This extension, Language Redirect, should indeed deal only with redirection, nothing more, nothing less. It has all the information it needs (FLang class from Frontend Localisation). Implementation wise: in the event keep only the logic that deals with the redirect. No delegates, no nothing. On any page that needs the redirect, attach the event.

Ta-da :)

**Comment by nitriques** [comment]
@vlad-ghita, @klaftertief 

Great that we are all on the same page !

I start the new extension probably today, I will keep you informed.

**Comment by vlad-ghita** [comment]
You don't need a new extension..

I think language redirect should take care of this. Is just a matter of cleaning it up and that's all.

**Comment by nitriques** [comment]
@vlad-ghita My motivation towards creating a new repro for this is only to be able to change the name.

Language redirect is not as clear as Frontend Localisation Redirect.

Since they will be coupled together, I think we really should consider renaming it (hence create a new repro for simplicity and backwards compatibility).

**Comment by vlad-ghita** [comment]
Ahh, fair point then.

**Comment by nitriques** [comment]
:) Would you prefer FLang Redirection ? FLang Event Redirection ? (like your FLang-gtld)... ?

**Comment by vlad-ghita** [comment]
`FLang Redirection` sounds perfect. `FLang Event Redirection` suggest the method of implementation of the redirect, which can change in time ;)

**Comment by nitriques** [comment]
@vlad-ghita I totally agree

**Comment by nitriques** [comment]
Done: https://github.com/DeuxHuitHuit/flang_redirection

Please test/post issues/bugs/feature request etc...
