### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by vlad-ghita** [klaftertief-symphony/language_redirect#3]
Please have a look at [this](http://symphony-cms.com/discuss/thread/71394) discussion in the forum.

I took responsibility to make the necessary modifications to add this feature.

For this to happen I have to move the logic for determining the language from `event.language_redirect.php` to `extension.driver.php` as the language is needed ASAP when a frontend page is required.

This can be accomplished by using the `@FrontendInitialised` delegate. I will put the required logic in here and leave in `_trigger` function only the redirect logic.

I said I'll do it but if you have the time and are willing to implement it, please let me know so we won't both work on it.

Thank you,

Vlad.

**Comment by klaftertief** [comment]
Sounds good.
I'm a bit short on time at the moment, so I'd be grateful if you could implement it.
