### ISSUE TITLE
.htaccess problem in ensamble

### ISSUE THREAD

**Issue by alexcristea** [klaftertief-symphony/language_redirect#6]
The .htaccess file does not contain the redirect ruleset after the exported ensamble is installed.

**Comment by klaftertief** [comment]
Thanks for reporting.

I'll try to find a way to add the rules back into the `.htaccess` when an endamble gets installed, though I don't have the time for it at the moment. For now you have to add the rules manually or resaving the preferences should do this for you.

**Comment by klaftertief** [comment]
There is already a fix available. See https://github.com/vlad-ghita/language_redirect/commit/2a08aec4c33c1801d5f637b3f462260bdb5d879c#L1R117 Will merge it soon.
